services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $apiKey: '%markocupic_cloudconvert.api_key%'

    Markocupic\CloudconvertBundle\:
        resource: ../../
        exclude: ../../{DependencyInjection,Resources}

