<?php

declare(strict_types=1);

/*
 * This file is part of Cloudconvert Bundle.
 *
 * (c) Marko Cupic 2022 <m.cupic@gmx.ch>
 * @license GPL-3.0-or-later
 * For the full copyright and license information,
 * please view the LICENSE file that was distributed with this source code.
 * @link https://github.com/markocupic/cloudconvert-bundle
 */

namespace Markocupic\CloudconvertBundle\Tests\Conversion;

use Contao\TestCase\ContaoTestCase;
use Markocupic\CloudconvertBundle\Conversion\ConvertFile;
use Markocupic\CloudconvertBundle\Logger\ContaoLogger;
use Symfony\Component\DependencyInjection\ContainerBuilder;

/**
 * Class ConvertFileTest.
 */
class ConvertFileTest extends ContaoTestCase
{
    private ContainerBuilder $container;
    private ConvertFile $cf;
    private string $filePath;

    protected function setUp(): void
    {
        $this->container = $this->getContainerWithContaoConfiguration('/tmp');
        $projectDir = $this->container->getParameter('kernel.project_dir');
        $this->container->setParameter('markocupic_cloudconvert.api_key', 'api_key');
        $apiKey = $this->container->getParameter('markocupic_cloudconvert.api_key');
        $logger = new ContaoLogger(null);
        $this->cf = new ConvertFile($logger, $apiKey);

        $this->filePath = $projectDir.'/files/msword.docx';
    }

    protected function tearDown(): void
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
    }

    public function testGetApiKey(): void
    {
        $this->cf->reset();

        $this->assertSame('api_key', $this->cf->getApiKey());

        $this->cf->setApiKey('custom_api_key');
        $this->assertSame('custom_api_key', $this->cf->getApiKey());
    }
}
